#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

WORKSPACE_DIR=$(realpath "${1:-.}")

mkdir -p $SCRIPT_DIR/.opencode/{config,share}

docker compose -f $SCRIPT_DIR/compose.yml run \
	--rm \
	-v $WORKSPACE_DIR:/root/workspace \
	opencode
